### ISSUE TITLE
hasPaperTrail is not a function - sequelize ^3.30.4

### ISSUE THREAD

**Issue by sany-v2** [nielsgl/sequelize-paper-trail#32]
I am getting the above error on trying the sample code .
I believe the error is because the way we initialize sequelize models is different .
Following is my code (relevant part)

```
 var sequelize = new Sequelize(config);  
 var db = {};  

  forEach(function (modelPath) {  

    var model = sequelize.import(path.resolve(modelPath));  

    db[model.name] = model;  

  }
 Object.keys(db).forEach(function (modelName) {  

  if (db[modelName].options.hasOwnProperty('associate')) {  

    db[modelName].options.associate(db);  

  }  

});  

var PaperTrail = require('sequelize-paper-trail').init(sequelize, {debug:true});  

PaperTrail.defineModels({db});  

db.User.Revisions = db.User.hasPaperTrail();  
```
  

Could you suggest some solution please.
Thanks.

**Comment by sany-v2** [comment]
Please ignore 'mean.js' in the title.

**Comment by sany-v2** [comment]
Hi,
I tested it with sequelize 4 , and it works. Is there a way to get this working with 3.30 ?

**Comment by nielsgl** [comment]
Unfortunately not that I know
